import haloCross from "../assets/43-haloWithGreek.jpg";
import alpaOmaga from "../assets/45-zaiRho.png";
import ippoCross from "../assets/44-ippoCross.png";
const englishText = {

    id: "englishText",
    titles: {
        russianChurch: "The Russian Church",
        holyFire: "The Holy Fire",
        holydays: "The Holidays of the Eastern Orthodox Church",
        crosses: "православных крестов",
        timeLine: "христианская хронология"
    },
    particularInfo: {
        russianChurch: `According to the tradition of the Eastern Churches (Orthodox – straight faith), they were founded by St. Andrew, one of the twelve apostles, during his visit at Scythia – a region that belonged to the Byzantine Empire, contemporary Eastern Europe.

        At the end of the first millenium CE, the eastern Slavic populations (from whom the Russians, Ukrainians and Belarusians developed) were heavily influenced by the culture of the neighboring Byzantine Empire. 
        Princess Olga, who ruled in Kiev as regent for her young son, was the first member of the royal family to accept Christianity during the course of her journey to Constantinople in 957. Olga’s son, Svyatoslav, did not express any interest in Christianity but his son Vladimir was baptized and through the implementation of a strategic plan, he led the christianization of most eastern Slavic population in 988 and adoption of byzantine Christianity by local ethnic groups.
        Initially, the Russian Church was subject to the Patriarch of Constatinople, who held the authority to appoint its leader. The leader of the Church was nominated “Metropolite of Kiev”. Because of Kiev’s weakening, the Metropolite’s base was moved to the city of Vladimir in 1299, and in 1329 it moved to Moscow, which constituted the epicenter of Russia. During the 15th century the Church played a central role concerning the liberation of the Russian people after nearly two centuries of Tatar rule. Figures like    Sergey Radonezhsky and Metropolite Alexey constituted spiritual leadership that operated hand-in-hand with the political leadership of Moscow’s princes to fulfill the cause of gaining independence for the Russian people.
        The middle of the 15th century finds the religious perception of the Eastern Churches, and the Russian Church in specific, being solidified. This perception was quite conservative concerning the performance of religious rites. That is to say, it was inclined to rely on Christian tradition as uttered by Jesus himself and spread by his apostles instead of later scriptures and commentaries.
        Approximately a hundred years following, in 1589, the Russian Church received formal recognition from all Eastern Churches and its leader got was nominated the title “Patriarch of Moscow and all Russia”. This was an additional step to the strengthening of the Church’s role, a process that evolved during this period because of the weakening of the political rule. As a result, the leaders of the Church were gradually getting incorporated in the political management of the country.
        Following the death of Patriarch Adrianos that was the head of the Church, Tsar Peter I decided not to appoint a new one but rather cancel the position altogether. Instead, Peter declared that from that point onwards not one man will stand as the leader of the Church, but rather an ecclesiastical council to be named the “Holy Synod”. In turn, this council was to be subject to the Tsar who would be its ultimate adjudicator. In this way Peter I limited the clergy’s power and actually subjugated to the state.
        This situation lasted almost 200 years, but when the Russian monarchy began losing its power, the Church took the respective measures to restore their former status. In a general conference that took place in the Kremlin on August 15th 1917, it was decided to restore the title of the Patriarch as it still remains to this day.
        Some months later, with the Bolsheviks rising to power following the October Revolution, the Church was compelled to deal with a crisis of unknown dimensions, similar to nothing it experienced in the past since its foundation. According to Marxist ideology, which viewed all expressions of religion as an obstacle to progress, the newly placed Bolshevik rule began a series of harsh persecutions against the Church. In addition to the anti-religious propaganda put in action across all social layers, a lot of churches and monasteries were closed, destroyed or converted into buildings for civil use by the government. A great number of priests and monks were either arrested, sent to exile or murdered.
        Disparities between the Russian Church and Western Christianity
        The Cross
        The prevalent Orthodox cross in Eastern Europe is different compared to the Latin cross, which is customary in most Western European countries and the American continent.
        In addition to the vertical and the horizontal lines of the Latin cross, there is another downward diagonal line, which symbolizes the two men crucified on Jesus’ side.
        The crucified man on Jesus’ right – Dismas, remembered as the good thief because he confessed his sins to Jesus and in return Jesus promised him a place in Heaven; this is the reason why this side of the line turns upwards. Dismas is venerated as a saint, protector of thieves and gravediggers, and Christian tradition has it that the cross on which Dismas was crucified made its way to Cyprus, where a liturgy dedicated to him takes place to this day.
        The crucified man on Jesus’ left – Gestas, remembered as the bad thief because he did not confess his sins before dying. Jesus indeed grants Dismas, the good thief, a place by his side in Heaven, but he does not bring ill on Gestas. The downward part of the line on the cross symbolizes Gestas’ lack of will for attonement and his decline to the Underworld because of it. 
        
        The Calendar
        The Russian Orthodox Church does not accept the Gregorian calendar (the commonly accepted in the West), but instead uses the Julian calendar for calculations of holiday and ceremony dates, which predates the Gregorian calendar.
        In Eastern Orthodoxy the Christmas period begins on the Nativity Fast, which begins forty days before Christmas. The Russian Orthodox Christmas period ends on the day of Epiphany, January 19th according to the Gregorian calendar. This day is commonly known as the feast day of Baptism, which commemorates Jesus’ baptism by John the Baptist. During the feast it is established that believers jump into the water, symbolizing the baptism, in order to find the cross that the priest threw to the water after blessing it.
        The Russian Orthodox New Year is celebrated on January 13th, acknowledged in Russia as the old New Year. Customs of the holiday mainly include bearing of the Star of Bethlehem, which commemorates Jesus’ coming as the beginning of the “period of grace” in the history of the world.
        
        Ritual elements of the Churches
        In Eastern Orthodox Churches no use of statues is being made, only of icons – figures of Christian tradition painted or depicted in a mosaic. Western Churches tend to make ritual use both in icons and three-dimensional statues. In Catholic churches the devotees confess their sins to a priest in a confessional whereas in Orthodox churches no use in confessional is made.
        In Eastern churches the believers cannot see the priest during the Divine Liturgy, as the iconostasis – a wall of icons and religious paintings – separates the flock from the priest. On the contrary, in Western churches the priest is exposed to the eyes of the flock.        
        `,
        holyFire: `
        The crowd is gathering in thousands in the streets leading to the Church of the Holy Sepulchre in Jerusalem and the churchyard is packed with people. The multitudes are flocking in the streets thinking that they are missing everything because of their distance from the heart of the church; however, they are definitely part of the ceremony, too. For orthodox Christians from Greece and Syria the ceremony of the Holy Fire constitutes the peak of the pilgrimage journey and holds tremendous importance. For us, Russian pilgrims, the Holy Fire ceremony does not possess such great significance, but there are some among us, as well, who perceive the reception of the Holy Fire as a remarkable miracle and undoubtedly an authentic event. Nevertheless, there are contrasting voices of high-ranking priests, who claim that “this is not an event mentioned in the Bible”, thus trying to belittle the event’s significance. Even if you are aligned with this group’s belief, during the ceremony of the Holy Fire you are holding a candle in your hands and longingly wait for the light to pass close enough to you so that you hold the miracle in your own hands. If you belong to the first group, which perceives the ceremony of the Holy Fire as a divine miracle, you most probably carry a tin-covered oil lamp in order to bring the Holy Fire back to your village. How is this done? I have no idea. The journey back from Jerusalem to Jaffa’s port is still graspable but how can someone preserve the fire on a voyage from Jaffa to Odessa? Careening for 15 days through storms so intense to the point the masts break? Sitting in nooks and corners in the deepest quarters of the ship that contain double the quantity of passengers the ship is supposed to carry? Eventually, the way from Odessa to the village on foot is the simplest part of the journey.
How would I want to make the journey back home with them, watch them safeguard the fire with utter devotion, opening their eyes from time to time just to ensure that the fire is still burning. I would like to watch them walk with their straight and firm postures around the Russian wilderness with the fire in their hands, passing on the light to hostel owners and any passer-by that would cross their way. I am very curious to witness the family’s reaction upon the pilgrim’s return from the journey with the same fire all along; the moment he will light the house oil-lamp and will preserve that same miraculous fire burn in it day by day.

The ceremony of the Holy Fire is a unique Christian ceremony performed by the Eastern Churches, taking place every year in the beginning of the Easter holiday, at Jesus’ tomb in the church of the Holy Sepulchre. At the time of the ceremony fire is miraculously lit on top of the tomb’s chapel.
The ceremony of the Holy Fire comes to pass every year on Holy Saturday, after Good Friday (commemorating Jesus’ crucifixion) during the observance of Easter holidays at the church of the Holy Sepulchre. This ritual is perceived as the most important one by the Eastern Churches, during which christian believers’ eyes all over the world turn to Jerusalem.
According to tradition, at 9 o’clock in the morning the Armenians open the church doors, and thousands of Christians from various communities, together with pilgrims, flow into the church and settle in every corner, each community to its respective wing. At 11 o’clock the Muslim guardians of the tomb that possess the key make their way from the aedicula of the tomb, after they have meticulously verified that the tomb does not contain any signs of fire or fire-lighting apparatus.
Under the auspices of the heads and representatives from the Eastern Churches, the entrance to Jesus’ tomb is sealed with wax. At 12:30 a procession with the Patriarch’s flags and trays begins and surrounds the aedicula thrice. The Patriarch enters after taking his ceremonial attire off; he is left with simple white clothes and does not carry any matches or lighter in his hands. The Patriarch enters the tomb’s chapel, followed by an Armenian bishop, and the door is shut after them. After an extended prayer recited by the Patriarch, fire is lit in the tomb’s chapel. Former Patriarchs’ testimonies include descriptions about the way in which the fire comes down from the sky, arises from the tomb and ignites the four beacons of 33 candles each, as Jesus’ age on the day of his crucifixion.
The Greek Patriarch and the Armenian bishop pass the fire on to the Armenian and Orthodox believers outside through the round apertures on the sides of the aedicula. Following, the Patriarch knocks on the closed door from the inside, the doors of the tomb are opened and representatives of the Syriac and Coptic Churches enter to take the fire to their communities. They wait until the two principal figures of the church come out of the aedicula and pass the fire around to the enthusiastic believers standing all around the church, shouting to each other in various languages: “Christ has risen!” (Greek – “Christos Anesti”).
The fire is passed on to the masses of believers, and from them to runners making haste with the fire to the numerous altars of each church in the city. The Holy Fire is then transported in a procession to central cities, such as Bethlehem and Nazareth, where it is received by the local community leader together with the majority of the people; members of all communitied, including Catholics and Muslims, participate in the celebrations and bring the fire to their homes. The Holy Fire is transported by special planes to Moscow, Athens, Kiev, Yerevan, Tbilisi, Bucharest, Kishinev and Sofia, where it is taken to the altar of each church where the celebrations of the Resurrection take place at midnight.
During the period of the Crusader Kingdom of Jerusalem the ceremony kept on taking place, even though the events of 1011 indicate that the crusaders had a hard time performing it: the fire was lit only after Baldwin I, king of Jerusalem, reached Templum Domini (the Dome of the Rock) and prayed in subservience.
After the fall of the Crusader Kingdom, the ceremony continued taking place. According to a source, Salah ad-Din demanded to be convinced about the miracle himself and visited the church on Holy Saturday of 1192.
During the years to come, the source of the testimonies concerning the ceremony is Catholic and Orthodox pilgrims. According to the testimony of the Archbishop of Nazareth, in 1580, the Armenians paid the Muslims in order to prevent the Greeks from entering the church and performing the ceremony. The latter stood in front of the closed gate of the church and prayed, and the fire got out from a crack in a column, left of the church door. According to this testimony, the double miracle caused the Muslim guard to acknowledge Jesus and to open the church doors he was guarding. Orthodox faith exalts the cracked column to this day.
The ceremony and its exact details solidified gradually over time, and a description of the ceremony written by a Russian pilgrim in 1652 appears to be very similar in the proceedings of the modern ceremony. Since the end of the 17th century, and Henry Maundell’s testimony, we know of pilgrims being present at the ceremony as spectators visiting the event, the religious ritual and the participants’ behavior. In 1834 a commotion broke out in the church of the Holy Sepulchre because of the congestion inside the church and the tensions among the different communities, during which some three hundred pilgrims lost their lives.
`,
    },
    crosses: {
        sibirCross: `mainly used in medieval art when depicting saints and represents the Holy Trinity. In Orthodox Christian and Byzantine art this cross frequently appears together with the Greek letters “Ο, Ω, Ν”, which stand for the Greek phrase “Ο ΩΝ” pointing to the name God told Moses when he asked him His name next to the burning bush - “I am that I am”. The use of these letters represent Jesus’ divinity.
    

        <img
        src=${haloCross}
        alt="humanitarian buildings"
        class="humanitarianBuildings"
      />    `,
        byzCross: `a cross with widened edges that was in commonplace use in the Early Byzantine Empire, which existed for over a thousand years and greatly influenced the course of history in the eastern Mediterranean and southern Europe, as well as contributed to the shaping of the essence in eastern Europe. Orthodox Christianity, which flourished in various regions of eastern Europe was deeply influenced by the Byzantine rite.`,
        russianCross: `symbol of the Russian Orthodox Church, whose origins are traced in 	the Byzantine Empire circa the 6th century. The upper horizontal line stands for the inscription above the cross on which Jesus was crucified written in Hebrew, Greek and Latin “Jesus the Nazarene, King of the Jews”. The lower diagonal line symbolizes good and evil. The upward part of this line represents, according to tradition, the “penitent thief” St. Dismas, who was crucified on Jesus’ right and confessed his sins. The downward part symbolizes the “impenitent thief” Gestas, who was crucified on Jesus’ left and did not confess his sins.`,
        jeruCross: ` also called “five-fold cross”, it consists of a large cross potent in the center surrounded by four smaller Greek crosses, one in each quadrant. This cross was used as the emblem of the Crusader Kingdom of Jerusalem since 1280. The five crosses represent the “Five Wounds of Christ” (one for each piercing wound Jesus suffered during the crucifixion). The four edges symbolize the four corners of the world. Today this cross is used by the Order of the Holy Sepulchre and appears in numerous places in the Christian world.
        The symbol of IOPS combines the chi-rho christogram together with alpha and omega with direct reference to the Greek cross and indirect reference to the Jerusalem cross.`,
        CRCross: `Chi Rho – one of the earliest forms of a christogram – a monogram related to Christianity. It is formed by the combination of the Greek letters chi (X) and rho (P) from the Greek word ΧΡΙΣΤΟΣ (Christos) – Jesus Christ. The symbol of chi rho was extensively used by the founder of the Byzantine Empire, Roman Caesar Constantine, waving in the sky upon his armies’ flags and was gradually preserved as a Christian emblem.
        Chi Rho with Alpha and Omega – Alpha, the first letter of the Greek alphabet and omega the last. As noted in the Book of Revelation, Jesus’ voice is heard by John after Jesus’ death, while he spreads Jesus’ doctrine on the island of Patmos. And as the verse from the Book of Revelation says “I am the Alpha and Omega”.

        <div class="cross-in-text-container">

                <img
                src=${alpaOmaga}
                alt="humanitarian buildings"
                class="cross-in-text"
                />        
                <img
                src=${ippoCross}
                alt="humanitarian buildings"
                class="cross-in-text"
            />
        </div>
         `,
        greekCross: `possess equal lines and has been in use sinc the 4th century. It was not intended to represent the crucifixion but rather the four cardinal directions and the spread of the message of Christianity to all four directions. Earlier testimonies concerning this cross can be found in the Babylonian Empire, where it represented the Sun God “Shamash”.`,
        patCross: `the upper horizontal line stands for the inscription above the cross on which Jesus was crucified written in Hebrew, Greek and Latin “Jesus the Nazarene, King of the Jews”.`
    },
    crossesTitles: {
        sibirCross: `Cross into a halo`,
        byzCross: `Byzantine cross`,
        russianCross: `Russian Orthodox cross`,
        jeruCross: `Jerusalem cross`,
        CRCross: `Chi Rho`,
        greekCross: `Greek cross`,
        patCross: `Patriarch’s cross`
    },
    holydays: {
        palmSunday: ` a common holiday for both the Eastern and the Western Church, one of the most archaic holidays of Christianity. The holiday begins on the Sunday before the week-long holiday of Easter (Pascha) and commemorates the painful way of suffering Jesus had to go through before crucifixion. During the holiday, processions are carried out, in which palm branches in the shape of a cross are distributed to the participants. Oftentimes the branches are blessed in sacred water and the participants accompany the procession shouting “Hosanna!”. Moreover, it is customary in several places for a donkey to be part of the procession as a symbol of the donkey on which the Messiah will enter Jerusalem, as pointed out in the Bible. Every culture performs the custom in a different way; for example, a statue of Jesus would be placed on the donkey or, as the tradition had it in Russia in the past, the Patriarch would ride on the donkey during the whole procession. In eastern traditions, a king riding a donkey was a sign of a peaceful arrival compared to a king riding a horse that was a sign of war.
        Palm Sunday was one of the peaks of the pilgrims’ journeys back in the day, and upon its arrival the complex of the church of the Holy Sepulchre would get festive and jubilant. Christians of all groups and denominations would overflow the church in masses, dressed up in their finest and most elegant traditional attires, while the Ottoman soldiers guarded the flooding churchyard. Thousands of believers held remnants from the biblical period, little ritual figurines, bouquets of flowers in various colors, lit candles and palm branches in the shape of a cross.               
        `,
        adventFeast: `also known as the 12th night, this is a feast day that celebrates the revelation of God incarnated as Jesus Christ. Eastern Christianity commemorates the baptism of Jesus in the Jordan river, while Western Christianity the revelation of Jesus Child in front of the three Magi. Across the majority of the Christian world the holiday is set on January 6th, twelve days after Christmas, and its origins can be found in early Orthodoxy.
        `,
        midsummer: `a holiday that begins every year on the longest day of the year. In Slavic countries that adhere to Orthodox Christianity, June 23rd (July 6th in Gregorian calendar) is known as the “night of Ivan” (John the Baptist) and is called “Kupala”. In some of these countries, like Russia and Ukraine, it is believed that this festivity predates Christianity. The holiday’s customs in the above mentioned countries are thematically connected to nature and fertility and they include bonfires and floating wreaths of flowers in rivers and streams.
        `,
        selenica: `a Slavic religious and folk holiday celebrated in Russia, Ukraine, Belarus and additional Slavic countries during the eighth week before Easter (Pascha).
        According to Russian Orthodox Christian tradition, this week of Maslenitsa marks the beginning of some of the practices of Great Lent (in commemoration of Jesus’ crucifixion) and meat eating is prohibited. For that reason this holiday is known as “Myasopustnaya Nedelya” (Russian – "мясопустная неделя"), which means “meat-fasting week”.
        Traditional delicacies of this holiday include pancakes filled with cheese and other dairy snacks. The widely known blinys are made of butter, eggs and milk, which are all prohibited since the week following – as Great Fast begins.
        Further customs of the holiday involve masquerade balls and sleigh rides. In different regions in Russia varied traditions have been developed for each day of this week; for instance, one day is dedicated to visiting family, one to visiting friends, another one is the day in which parades with straw effigies and another dedicated to sleigh rides. Another distinct custom is the creation and burning of a straw effigy known as “Miss Maslenitsa” on the last day of this festive week, the night before the beginning of Great Fast.                 
        `,
        transformation: `one of the 12 most important holidays in the religious calendar according to Orthodox Christianity, which is celebrated on August 6th (August 19th in Gregorian calendar). Tradition has it to bring grapes, apples or other fruit to the church and “the blessing of First Fruit” of the year. The holiday is related to Jesus and the Holy Trinity, as God spoke from the Heavens during this day accompanied by the presence of the Holy Ghost in the form of a cloud.`
    },
    holydaysTitles: {
        palmSunday: "Palm Sunday",
        adventFeast: "Epiphany/Theophany",
        midsummer: "Mid-Summer Holiday",
        selenica: "Maslenitsa",
        transformation: "Feast of the Transfiguration"
    },
}
export { englishText as default };